version: 2
jobs:
  build:
    docker:
      - image: cimg/node:12.18

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: role-ui-cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: role-ui-cache-{{ checksum "package-lock.json" }}

      - run: npm run test
